baseurl:     "/wdk"

# Latest version for outputting deprecated messages
wdk_version: "1.1"

host: 192.168.3.241
port: 4012

# Conversion
markdown:    kramdown

# Turn on recognition of 'Github Flavored Markdown'
kramdown:
  input: GFM

# Backwards-compatibility
relative_permalinks: false

# Sass
sass:
    sass_dir: _sass
    style: :compressed

collections:
  tutorials:
    output: true
  glossary:
    output: true
